### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by Deep-Dark-Forest** [PCL-Community/PCL2-LogViewer-CE#1]
目前无法正确编译`main.c`，@wuyuncheng-26 你来看一下咋回事（

**Comment by wuyuncheng-26** [comment]
让我康康

**Comment by wuyuncheng-26** [comment]
![image](https://github.com/PCL-Community/PCL2-LogViewer-CE/assets/122529705/3cd772ba-b761-4a80-b928-7a65baa9d712)
噔噔咚

**Comment by wuyuncheng-26** [comment]
一堆 warning 和 error
是屎山代码没错了（

**Comment by wuyuncheng-26** [comment]
@chichundan 可以解释一下您的代码吗（

**Comment by hejiehao** [comment]
> 一堆 warning 和 error 是屎山代码没错了（

~~防御性编程~~

**Comment by chichundan** [comment]
额，其实我这个也只是个半成品（
@Deep-Dark-Forest 谁让你编译了（

**Comment by hejiehao** [comment]
![image](https://github.com/PCL-Community/PCL2-LogViewer-CE/assets/98140773/e8d58a11-5a70-4948-a96e-1ae85af89802)

**Comment by wuyuncheng-26** [comment]
啊哈哈

**Comment by wuyuncheng-26** [comment]
难绷
